name: "Install yq"
description: "Install yq using a direct download"
inputs:
  version:
    description: "yq version"
    default: v4.45.1
  arch:
    description: "host arch"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install yq
      shell: bash
      run: |
        set -e
        ARCH=${{ inputs.arch }}
        if [[ "$ARCH" == "x64" || "$ARCH" == "amd64" ]]; then
          YQ_ARCH="amd64"
        elif [[ "$ARCH" == "arm64" ]]; then
          YQ_ARCH="arm64"
        else
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi
        YQ_VERSION=${{ inputs.version }}
        wget -q "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${YQ_ARCH}" -O /tmp/yq
        chmod +x /tmp/yq
        echo "/tmp" >> $GITHUB_PATH
        /tmp/yq --version || { echo "Failed to run yq --version"; exit 1; }
