name: "Install yq"
description: "Install yq from source"
inputs:
  version:
    description: "yq version"
    default: v4.45.1
  arch:
    description: "host arch"
    required: true
  use-sudo:
    description: "use sudo to move the yq binary"
    default: false
runs:
  using: "composite"
  steps:
    - name: Install yq
      shell: bash
      run: |
        set -e
        YQ_VERSION=${{ inputs.version }}
        ARCH=${{ inputs.arch }}
        if [[ "$ARCH" != "amd64" && "$ARCH" != "arm64" ]]; then
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi
        curl -fsL https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${ARCH}.tar.gz -o /tmp/yq.tar.gz
        tar -xzf /tmp/yq.tar.gz -C /tmp
        ls -l /tmp  # Debug: List extracted files
        if [[ ! -f /tmp/yq_linux_${ARCH} ]]; then
          echo "Error: yq_linux_${ARCH} not found after extraction"
          exit 1
        fi
        chmod +x /tmp/yq_linux_${ARCH}
        file /tmp/yq_linux_${ARCH}  # Debug: Check binary type
        ${{ inputs.use-sudo == 'true' && 'sudo' || '' }} mv /tmp/yq_linux_${ARCH} /usr/bin/yq
        yq --version  # Debug: Verify yq installation
