name: "Install yq"
description: "Install yq using a Docker container"
inputs:
  version:
    description: "yq version"
    default: v4.45.1
  arch:
    description: "host arch"
    required: true
  use-sudo:
    description: "use sudo to install yq"
    default: false
runs:
  using: "composite"
  steps:
    - name: Install yq via Docker
      shell: bash
      run: |
        set -e
        ARCH=${{ inputs.arch }}
        if [[ "$ARCH" != "amd64" && "$ARCH" != "arm64" ]]; then
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi
        # Create a wrapper script to run yq in a Docker container
        echo '#!/bin/bash' > /usr/bin/yq
        echo 'docker run --rm -v $(pwd):/workdir mikefarah/yq:${{ inputs.version }} "$@"' >> /usr/bin/yq
        chmod +x /usr/bin/yq
        ${{ inputs.use-sudo == 'true' && 'sudo' || '' }} mv /usr/bin/yq /usr/bin/yq
        yq --version
