name: "Install yq"
description: "Install yq using snap"
inputs:
  version:
    description: "yq version"
    default: v4.45.1
  arch:
    description: "host arch"
    required: true
  use-sudo:
    description: "use sudo to install yq"
    default: false
runs:
  using: "composite"
  steps:
    - name: Install yq via snap
      shell: bash
      run: |
        set -e
        ARCH=${{ inputs.arch }}
        if [[ "$ARCH" != "amd64" && "$ARCH" != "arm64" ]]; then
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi
        ${{ inputs.use-sudo == 'true' && 'sudo' || '' }} snap install yq
        # Ensure snap bin directory is in PATH
        export PATH=$PATH:/snap/bin
        echo "PATH=$PATH:/snap/bin" >> $GITHUB_ENV
        # Verify yq is accessible
        which yq || { echo "yq not found in PATH"; exit 1; }
        # Check permissions
        ls -l $(which yq)
        yq --version || { echo "Failed to run yq --version"; exit 1; }
