#!/usr/bin/env bash
echo "-- chart/test --"
set -ex
if [ ! -f /tmp/helm_v3 ]; then
    echo "helm_v3 not found at /tmp/helm_v3. Helm is required to run tests."
    exit 1
fi
if [ "${ARCH}" != "amd64" ]; then 
    echo "${ARCH} is not supported for chart tests, chart tests won't run"
    exit 0
fi
chart_dir=$(dirname $0)/../../build/chart/rancher
if [ ! -d "$chart_dir" ]; then
    echo "Chart directory $chart_dir not found"
    exit 1
fi
/tmp/helm_v3 unittest --help >/dev/null 2>&1
if [[ $? > 0 ]]; then
    echo "helm plugin unittest not found at /tmp/helm_v3."
    exit 1
fi
current_dir=$(pwd)
cd "$chart_dir"
/tmp/helm_v3 unittest ./
cd "$current_dir"
