name: Create images files
on:
  workflow_call:
jobs:
  create-images-files:
    runs-on: runs-on,runner=2cpu-linux-x64,image=ubuntu22-full-x64,run-id=${{ github.run_id }}
    permissions:
      contents: write
      id-token: write
    env:
      REGISTRY: ""
      CHECKSUM_FILE: "sha256sum.txt"
      ARTIFACTS_BASE_DIR: "bin"
    env:
      AWS_DEFAULT_REGION: "us-east-1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment Variables
        uses: ./.github/actions/setup-tag-env
      - id: env 
        name: Setup Dependencies Env Variables
        uses: ./.github/actions/setup-build-env
      - uses: actions/setup-go@v5
        with:
          go-version: '${{ steps.env.outputs.GO_VERSION }}'
      - name: Download data.json
        run: |
          mkdir -p bin
          curl -sLf https://releases.rancher.com/kontainer-driver-metadata/${{ steps.env.outputs.CATTLE_KDM_BRANCH }}/data.json > ./bin/data.json
          cp ./bin/data.json ./bin/rancher-data.json
      - name: Create k3s images file
        uses: ./.github/actions/k3s-images
        with:
          k3s_version: ${{ steps.env.outputs.CATTLE_K3S_VERSION }}
      - name: Create files
        run: |
          mkdir -p $HOME/bin
          touch $HOME/bin/rancher-rke-k8s-versions.txt
      - name: Create components and images files
        shell: bash
        run: ./scripts/create-components-images-files.sh
      - name: Move rke-k8s version file
        run: mv $HOME/bin/rancher-rke-k8s-versions.txt ./bin
      - name: Create sha256sum.txt file
        run: ./scripts/artifacts-hashes.sh
      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/prime-artifacts-uploader-access/credentials token | PRIME_ARTIFACTS_UPLOADER_ACCESS_KEY ;
            secret/data/github/repo/${{ github.repository }}/prime-artifacts-uploader-secret/credentials token | PRIME_ARTIFACTS_UPLOADER_SECRET_KEY ;
      - name: Generate sha256sum file and upload artifacts
        env:
          AWS_ACCESS_KEY_ID: ${{ env.PRIME_ARTIFACTS_UPLOADER_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ env.PRIME_ARTIFACTS_UPLOADER_SECRET_KEY }}
        shell: bash
        run: |
          set -ex

          artifacts=(
            "rancher-components.txt"
            "rancher-data.json"
            "rancher-images-origins.txt"
            "rancher-images-sources.txt"
            "rancher-images.txt"
            "rancher-load-images.ps1"
            "rancher-load-images.sh"
            "rancher-mirror-to-rancher-org.ps1"
            "rancher-mirror-to-rancher-org.sh"
            "rancher-rke-k8s-versions.txt"
            "rancher-save-images.ps1"
            "rancher-save-images.sh"
            "rancher-windows-images-sources.txt"
            "rancher-windows-images.txt"
          )

          for artifact in "${artifacts[@]}"; do
            mv "./bin/$artifact" "./dist/$artifact"
          done

          ./scripts/artifacts-hashes.sh ./dist

          artifacts+=("$CHECKSUM_FILE")

          for artifact in "${artifacts[@]}"; do
            aws s3 cp "./dist/$artifact" "s3://prime-artifacts/rancher/${{ env.TAG }}/$artifact"
          done
      - name: Build artifacts index
        env:
          ARTIFACTS_DISTRIBUTION_ID: EUK3RJTBZG1QG
        uses: ./.github/actions/build-artifacts-index
