name: Merge agent manifest
on:
  workflow_call:
jobs:
  merge-agent-manifest:
    runs-on: runs-on,runner=2cpu-linux-x64,image=ubuntu22-full-x64,run-id=${{ github.run_id }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment Variables
        uses: ./.github/actions/setup-tag-env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Create manifest list and push
        run: |
          # docker manifest is used with windows images to maintain os.version in the manifest
          docker manifest create ${{ env.REGISTRY }}/rancher-agent:${{ env.TAG }} \
            ${{ env.REGISTRY }}/rancher-agent:${{ env.TAG }}-windows-2019 \
            ${{ env.REGISTRY }}/rancher-agent:${{ env.TAG }}-windows-2022

          docker manifest push ${{ env.REGISTRY }}/rancher-agent:${{ env.TAG }}

          # docker buildx imagetools create pushes to the registry by default, which is not the same behavior as docker manifest create
          docker buildx imagetools create -t ${{ env.REGISTRY }}/rancher-agent:${{ env.TAG }} \
            --append ${{ env.REGISTRY }}/rancher-agent:${{ env.TAG }}-amd64 \
            --append ${{ env.REGISTRY }}/rancher-agent:${{ env.TAG }}-arm64 

          if [[ "${{ github.ref_name }}" == release/v* ]] || [[ "${{ github.ref_name }}" == "main" ]]; then
            docker manifest create ${{ env.REGISTRY }}/rancher-agent:${{ env.HEAD_TAG }} \
              ${{ env.REGISTRY }}/rancher-agent:${{ env.TAG }}-windows-2019 \
              ${{ env.REGISTRY }}/rancher-agent:${{ env.TAG }}-windows-2022
            docker manifest push ${{ env.REGISTRY }}/rancher-agent:${{ env.HEAD_TAG }}

            docker buildx imagetools create -t ${{ env.REGISTRY }}/rancher-agent:${{ env.HEAD_TAG }} \
              --append ${{ env.REGISTRY }}/rancher-agent:${{ env.TAG }}-amd64 \
              --append ${{ env.REGISTRY }}/rancher-agent:${{ env.TAG }}-arm64 
          fi
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/rancher-agent:${{ env.TAG }}

