name: Rancher Release for v2.10.3
on:
  push:
    tags:
      - "v2.10.3"
env:
  COMMIT: ${{ github.sha }}
  REPOSITORY_OWNER: kalexiwells
  IMAGE: kalexiwells/rancher-images
  IMAGE_AGENT: kalexiwells/rancher-agent
  IMAGE_INSTALLER: kalexiwells/system-agent-installer-rancher
  REGISTRY: docker.io
jobs:
  build-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [x64, arm64]
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v2.10.3
      - name: Setup and build
        uses: ./.github/actions/build-images/server
  build-agent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [x64, arm64]
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v2.10.3
      - name: Setup and build
        uses: ./.github/actions/build-images/agent
  build-installer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [x64, arm64]
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v2.10.3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup and build
        uses: ./.github/actions/build-images/installer
  push-images:
    needs: [build-server, build-agent]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [x64, arm64]
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v2.10.3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push images
        uses: ./.github/actions/push-images
  merge-server-manifest:
    needs: [push-images]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v2.10.3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Merge manifest
        uses: ./.github/actions/merge-manifests/server
  merge-agent-manifest:
    needs: [push-images]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v2.10.3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Merge manifest
        uses: ./.github/actions/merge-manifests/agent
  merge-installer-manifest:
    needs: [build-installer]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v2.10.3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Merge manifest
        uses: ./.github/actions/merge-manifests/installer
