name: Unit Tests
on: [workflow_dispatch, workflow_call]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run unit tests
        run: go test -cover -tags=test ./pkg/...

