name: Validate
on: [pull_request, push]
jobs:
  validate:
    runs-on: ubuntu-latest
    container: python:3.11-slim
    env:
      GOLANG_CI_LINT_VERSION: v1.54.2
      GOLANG_VERSION: '1.23'
    steps:
      - name: Install dependencies
        shell: bash
        run: |
          apt-get update
          apt-get install -y git
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Python version
        run: |
          python3 --version
          python3 -m ensurepip --upgrade
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: Install Python and dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install tox flake8
      - name: Validate
        run: ./scripts/validate
