name: Verify generated code changes

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - 'release/*'

env:
  MAIN_BRANCH: origin/master
  GOARCH: amd64
  CGO_ENABLED: 0
  SETUP_GO_VERSION: '1.23.*'

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      -
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}
      -
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Verify go.mod status
        run: ./.github/scripts/check-for-go-mod-changes.sh
      -
        name: Install controller-gen
        run: go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0
      -
        name: Verify auto-generated changes
        run: ./.github/scripts/check-for-auto-generated-changes.sh
